import { CharacterAsset, Advertiser, AdCampaign } from "../types/campaign";

export const MOCK_CHARACTERS: CharacterAsset[] = [
  {
    id: "target_aim_hero",
    name: "Precision Target Hero",
    category: "Adaptive Sports & Archery",
    icon: "🎯",
    description: "Precision adaptive athlete targeting independence and excellence.",
    defaultCta: "Adaptive Sports Catalog",
    defaultBubble: "Hit your target mobility goals with precision!",
    themeColor: "#8b5cf6",
    badge: "Precision Hero",
    speedMultiplier: 1.1,
    defaultFlagShape: "ribbon",
    isCustom: true,
    rigging: {
      hasWheelSpin: true,
      hasBlinkingEyes: true,
      hasGazeTracking: true,
      hasBreathingTorso: true,
      hasWavingArm: true,
      hasScarfRipple: true,
      hasTailWag: false,
    },
    baseTemplate: "runner",
  },
  {
    id: "wheelchair_boy",
    name: "Max Wheelchair Hero",
    category: "Wheelchairs",
    icon: "♿",
    description: "Active hero in manual wheelchair with rotating spoke wheels, breathing torso, and eye gaze tracking.",
    defaultCta: "Click to See Our Wheelchairs",
    defaultBubble: "Freedom Mobility Solutions",
    themeColor: "#2563eb",
    badge: "Popular Hero",
    speedMultiplier: 1.0,
    defaultFlagShape: "swallowtail",
  },
  {
    id: "accessible_van",
    name: "Voyager Welcab Van",
    category: "Vehicles",
    icon: "🚐",
    description: "Aerodynamic Welcab van with rotating alloy wheels, glowing headlights, and waving driver.",
    defaultCta: "Click to See Accessible Vans",
    defaultBubble: "Certified Welcab Vans Australia",
    themeColor: "#0284c7",
    badge: "Premium Vehicle",
    speedMultiplier: 1.25,
    defaultFlagShape: "ribbon",
  },
  {
    id: "mobility_scooter",
    name: "Apex 4-Wheel Scooter",
    category: "Scooters",
    icon: "🛵",
    description: "4-wheel electric mobility scooter with tiller controls, front grocery basket, and friendly driver.",
    defaultCta: "Click to See Mobility Scooters",
    defaultBubble: "All-Terrain Mobility Scooters",
    themeColor: "#ef4444",
    badge: "High Range",
    speedMultiplier: 0.95,
    defaultFlagShape: "pennant",
  },
  {
    id: "care_nurse",
    name: "Nurse Sarah",
    icon: "🩺",
    category: "Care & Health",
    description: "Compassionate care nurse in scrubs with stethoscope, riding an electric medical caddy.",
    defaultCta: "Home Care Mobility Aids",
    defaultBubble: "Certified NDIS Community Care",
    themeColor: "#0d9488",
    badge: "Clinical Care",
    speedMultiplier: 0.9,
    defaultFlagShape: "ribbon",
  },
  {
    id: "doctor_specialist",
    name: "Dr. Harrison",
    icon: "👨‍⚕️",
    category: "Clinical Assessments",
    description: "Mobility & OT specialist in white consultation coat with stethoscope and digital tablet.",
    defaultCta: "Clinical Assessments",
    defaultBubble: "NDIS Registered OT Prescriptions",
    themeColor: "#2563eb",
    badge: "Specialist Approved",
    speedMultiplier: 1.0,
    defaultFlagShape: "box",
  },
  {
    id: "guide_dog_duo",
    name: "Maya & Guide Dog Barnaby",
    icon: "🦮",
    category: "Sensory & Vision",
    description: "Visually impaired handler with white cane accompanied by a loyal Golden Retriever with wagging tail.",
    defaultCta: "Sensory & Vision Aids",
    defaultBubble: "Empowering Independent Living",
    themeColor: "#8b5cf6",
    badge: "Assistance Partner",
    speedMultiplier: 0.85,
    defaultFlagShape: "swallowtail",
  },
  {
    id: "prosthetic_athlete",
    name: "Jordan Blade Runner",
    icon: "🏃",
    category: "Active Sports",
    description: "Active Paralympic runner with high-tech carbon-fiber running blade and athletic singlet.",
    defaultCta: "Active Sports Equipment",
    defaultBubble: "High Performance Prosthetics",
    themeColor: "#10b981",
    badge: "Active Performance",
    speedMultiplier: 1.4,
    defaultFlagShape: "ribbon",
  },
];

export const MOCK_ADVERTISERS: Advertiser[] = [
  {
    id: "adv_abc_mobility",
    name: "Precision Mobility Australia",
    logoText: "PM",
    contactEmail: "contact@precisionmobility.com.au",
    websiteUrl: "https://precisionmobility.com.au",
    rating: 5.0,
    totalListings: 32,
    itemsForSale: [
      {
        id: "item_target_1",
        title: "Precision Target Adaptive Sports Chair & Archery Rig",
        price: "$6,450",
        imageBg: "from-purple-600 to-indigo-900",
        category: "Adaptive Sports",
        badge: "NDIS Approved",
        description: "Custom titanium frame with precision stabilizer mounts for archery and athletics.",
        specs: ["Custom Fit", "Titanium Alloy", "5 Yr Warranty"],
      },
    ],
  },
  {
    id: "adv_freedom_chairs",
    name: "Freedom Mobility Direct",
    logoText: "FM",
    contactEmail: "info@freedommobility.com.au",
    websiteUrl: "https://freedommobility.com.au",
    rating: 4.8,
    totalListings: 18,
    itemsForSale: [
      {
        id: "item_wc_1",
        title: "ErgoLite 2 Ultra-Lightweight Folding Wheelchair",
        price: "$1,150",
        imageBg: "from-emerald-600 to-teal-800",
        category: "Wheelchairs",
        badge: "Top Rated",
        description: "Weighs only 8.7 kg, aircraft grade alloy frame, fold-down backrest.",
        specs: ["8.7 kg Total", "Aircraft Alloy", "Compact Fold"],
      },
    ],
  },
];

export const INITIAL_CAMPAIGNS: AdCampaign[] = [
  {
    id: "camp_target_999",
    advertiserName: "Precision Mobility Australia",
    advertiserId: "adv_abc_mobility",
    characterId: "target_aim_hero",
    ctaText: "Precision Target Range",
    bubbleText: "🎯 Hit your mobility goals with 100% precision!",
    flagShape: "ribbon",
    wheelColor: "#8b5cf6",
    characterSize: "large",
    campaignMode: "SOLO",
    targetUrl: "/seller/adv_abc_mobility",
    clickBehavior: "MODAL",
    assignedPages: ["all", "home"],
    startDate: "2026-10-01",
    endDate: "2026-12-31",
    status: "ACTIVE",
    impressions: 2150,
    clicks: 340,
    createdAt: "2026-10-04",
  },
  {
    id: "camp_wheelchair_101",
    advertiserName: "Freedom Welcab Australia",
    advertiserId: "adv_abc_mobility",
    characterId: "wheelchair_boy",
    ctaText: "20+ Welcab Vans In Stock",
    bubbleText: "G'day! Looking for wheelchair vans or mobility aids?",
    flagShape: "swallowtail",
    accessory: "cape",
    wheelColor: "#2563eb",
    characterSize: "large",
    campaignMode: "SOLO",
    targetUrl: "/seller/adv_abc_mobility",
    clickBehavior: "MODAL",
    assignedPages: ["all", "home", "vans"],
    startDate: "2026-10-01",
    endDate: "2026-12-31",
    status: "ACTIVE",
    impressions: 1420,
    clicks: 184,
    createdAt: "2026-10-01",
  },
  {
    id: "camp_van_202",
    advertiserName: "Freedom Mobility Direct",
    advertiserId: "adv_freedom_chairs",
    characterId: "accessible_van",
    ctaText: "Certified Welcab Vans",
    bubbleText: "Certified Toyota HiAce & Alphard Welcabs with electric ramps!",
    flagShape: "ribbon",
    accessory: "crown",
    wheelColor: "#0284c7",
    characterSize: "large",
    campaignMode: "SOLO",
    targetUrl: "/seller/adv_freedom_chairs",
    clickBehavior: "MODAL",
    assignedPages: ["all", "home"],
    startDate: "2026-10-01",
    endDate: "2026-12-31",
    status: "ACTIVE",
    impressions: 980,
    clicks: 112,
    createdAt: "2026-10-01",
  },
];
