import { CharacterAsset, Advertiser, AdCampaign } from "../types/campaign";

export const MOCK_CHARACTERS: CharacterAsset[] = [
  {
    id: "wheelchair_boy",
    name: "Wheelchair Cruiser & Flag",
    category: "Wheelchairs",
    icon: "🧑‍🦼",
    description: "Active boy in manual wheelchair pulling a ribbon CTA flag behind him.",
    defaultCta: "Click to See Our Wheelchairs",
    defaultBubble: "Freedom Mobility",
    themeColor: "#2563eb",
    badge: "Popular Ad Slot",
    speedMultiplier: 1.0,
    defaultFlagShape: "swallowtail",
  },
  {
    id: "accessible_van",
    name: "Branded Minivan & Banner",
    category: "Vehicles",
    icon: "🚐",
    description: "Accessible van with side ramp, custom logo & trailing dynamic banner.",
    defaultCta: "Click to See Accessible Vans",
    defaultBubble: "Accessible Transport",
    themeColor: "#0284c7",
    badge: "Premium Van Slot",
    speedMultiplier: 1.25,
    defaultFlagShape: "ribbon",
  },
  {
    id: "scooter_nurse",
    name: "Scooter & Care Guide Dog",
    category: "Scooters & Care",
    icon: "🛵",
    description: "Lady on mobility scooter with support nurse walking a guide dog.",
    defaultCta: "Click to See Mobility Scooters",
    defaultBubble: "Support Services",
    themeColor: "#16a34a",
    badge: "High Engagement",
    speedMultiplier: 0.85,
    defaultFlagShape: "swallowtail",
  },
  {
    id: "electric_chair",
    name: "PowerGlide Pro Chair",
    category: "Power Wheelchairs",
    icon: "🦼",
    description: "High-tech power wheelchair with LED controls and dynamic banner.",
    defaultCta: "Click to See Power Wheelchairs",
    defaultBubble: "Ultra Light Power",
    themeColor: "#7c3aed",
    badge: "New Arrival",
    speedMultiplier: 1.1,
    defaultFlagShape: "pennant",
  },
  {
    id: "stairlift_pro",
    name: "EasyClimb Home Stairlift",
    category: "Home Accessibility",
    icon: "🛗",
    description: "Smooth rail stairlift character for home mobility campaigns.",
    defaultCta: "Click for Home Stairlift Deals",
    defaultBubble: "Home Accessibility",
    themeColor: "#ea580c",
    badge: "Home Care Slot",
    speedMultiplier: 0.9,
    defaultFlagShape: "box",
  },
  {
    id: "walker_lady",
    name: "Active Rollator Walker Senior",
    category: "Daily Living Aids",
    icon: "🦯",
    description: "Energetic senior walking with 4-wheel rollator walker & shopping basket.",
    defaultCta: "Click to See Mobility Walkers",
    defaultBubble: "Daily Independence",
    themeColor: "#059669",
    badge: "Senior Special",
    speedMultiplier: 0.95,
    defaultFlagShape: "swallowtail",
  },
  {
    id: "guide_dog_duo",
    name: "Guide Dog & Handler",
    category: "Assistance Animals",
    icon: "🦮",
    description: "Person with vision impairment walking confidently with trained guide dog in harness.",
    defaultCta: "Click to Explore Assistance Services",
    defaultBubble: "Guide Dog Services",
    themeColor: "#b45309",
    badge: "Accessibility Hero",
    speedMultiplier: 1.05,
    defaultFlagShape: "swallowtail",
  },
  {
    id: "hearing_aid_teen",
    name: "Hearing Aid Teen",
    category: "Hearing Devices",
    icon: "🎧",
    description: "Cool teenager with modern behind-the-ear hearing aid, skateboard under arm.",
    defaultCta: "Click to See Hearing Devices",
    defaultBubble: "Clear Sound, Clear Life",
    themeColor: "#0891b2",
    badge: "Youth Engagement",
    speedMultiplier: 1.3,
    defaultFlagShape: "pennant",
  },
  {
    id: "prosthetic_athlete",
    name: "Blade Runner Athlete",
    category: "Prosthetics",
    icon: "🏃",
    description: "Athletic runner with carbon fibre blade prosthetic leg, sprinting with a flag.",
    defaultCta: "Click to See Prosthetic Solutions",
    defaultBubble: "No Limits Running!",
    themeColor: "#dc2626",
    badge: "Inspiration Slot",
    speedMultiplier: 1.6,
    defaultFlagShape: "pennant",
  },
  {
    id: "crutches_kid",
    name: "Adventure Kid on Crutches",
    category: "Crutches & Supports",
    icon: "🧒",
    description: "Energetic child on forearm crutches wearing a superhero cape.",
    defaultCta: "Click to See Crutch Options",
    defaultBubble: "Superhero on the Move!",
    themeColor: "#7c3aed",
    badge: "Kids Special",
    speedMultiplier: 0.9,
    defaultFlagShape: "ribbon",
  },
  {
    id: "delivery_trike",
    name: "Adaptive Cargo Trike",
    category: "Adaptive Vehicles",
    icon: "🚲",
    description: "Three-wheeled adaptive cargo tricycle delivering mobility equipment with a branded crate.",
    defaultCta: "Click for Mobility Delivery Services",
    defaultBubble: "Fast Local Delivery!",
    themeColor: "#0d9488",
    badge: "Service Hero",
    speedMultiplier: 1.15,
    defaultFlagShape: "box",
  },
  {
    id: "sign_language_duo",
    name: "Sign Language Duo",
    category: "Communication Aids",
    icon: "🤟",
    description: "Two people signing to each other — a joyful interaction promoting communication aids.",
    defaultCta: "Click for Communication Aids",
    defaultBubble: "Speak with Your Hands!",
    themeColor: "#a21caf",
    badge: "Communication Slot",
    speedMultiplier: 0.88,
    defaultFlagShape: "swallowtail",
  },
];

export const MOCK_ADVERTISERS: Advertiser[] = [
  {
    id: "adv_abc_mobility",
    name: "ABC Mobility Solutions",
    logoText: "ABC Mobility",
    contactEmail: "sales@abcmobility.com",
    websiteUrl: "https://example.com/abcmobility",
    rating: 4.9,
    totalListings: 18,
    itemsForSale: [
      {
        id: "item_van_1",
        title: "2023 Ford Transit Custom Welcab Ramp Van",
        price: "$52,900",
        imageBg: "from-blue-500 to-indigo-600",
        category: "Accessible Van",
        badge: "Certified Direct",
        description: "Lowered floor side-entry van with automated power ramp and tie-downs.",
        specs: ["14,200 miles", "Remote electric ramp", "4 wheelchair lock-in spots", "Full 3-year warranty"]
      },
      {
        id: "item_van_2",
        title: "2022 Toyota Alphard Welcab Swivel Seat",
        price: "$46,500",
        imageBg: "from-sky-500 to-blue-600",
        category: "Passenger Minivan",
        badge: "Low Mileage",
        description: "Luxury interior passenger swivel seat with rear ramp access.",
        specs: ["8,900 miles", "Automatic swivel passenger seat", "Dual climate control", "Leather interior"]
      }
    ]
  },
  {
    id: "adv_freedom_chairs",
    name: "Freedom Mobility & Chairs",
    logoText: "FreedomChairs",
    contactEmail: "info@freedomchairs.com",
    websiteUrl: "https://example.com/freedomchairs",
    rating: 4.8,
    totalListings: 24,
    itemsForSale: [
      {
        id: "item_wc_1",
        title: "PowerGlide Pro Foldable Electric Wheelchair",
        price: "$2,450",
        imageBg: "from-purple-500 to-indigo-700",
        category: "Power Wheelchair",
        badge: "Bestseller",
        description: "Lightweight aircraft aluminum power chair folds in 3 seconds.",
        specs: ["Airline approved lithium battery", "15 mile range", "28 lbs total weight", "360° joystick"]
      },
      {
        id: "item_wc_2",
        title: "ErgoLite Ultralight Companion Wheelchair",
        price: "$890",
        imageBg: "from-indigo-400 to-blue-600",
        category: "Manual Wheelchair",
        badge: "Top Rated",
        description: "Ultra-compact transport chair with memory foam seat cushion.",
        specs: ["Folds into carry bag", "Seat belt included", "Anti-tippers", "Removable footrests"]
      }
    ]
  },
  {
    id: "adv_apex_scooters",
    name: "Apex Scooter & Care Co.",
    logoText: "Apex Care",
    contactEmail: "hello@apexcare.com",
    websiteUrl: "https://example.com/apexscooters",
    rating: 4.9,
    totalListings: 15,
    itemsForSale: [
      {
        id: "item_sc_1",
        title: "Apex Turbo 4-Wheel All-Terrain Mobility Scooter",
        price: "$3,190",
        imageBg: "from-emerald-500 to-teal-700",
        category: "4-Wheel Scooter",
        badge: "Customer Favorite",
        description: "Luxury swivel captain chair with front basket & full suspension.",
        specs: ["12 mph top speed", "25 mile battery range", "High beam LED lighting", "USB phone charger"]
      }
    ]
  }
];

export const INITIAL_CAMPAIGNS: AdCampaign[] = [
  {
    id: "camp_wheelchair_101",
    advertiserName: "Suraj Mobility Solutions",
    advertiserId: "adv_abc_mobility",
    characterId: "wheelchair_boy",
    characterSize: "large",
    campaignMode: "SOLO",
    ctaText: "Suraj Mobility Solutions — Explore All Ads",
    bubbleText: "Suraj Mobility Solutions",
    flagShape: "swallowtail",
    targetUrl: "https://example.com/surajmobility",
    clickBehavior: "MODAL",
    assignedPages: ["all", "home", "wheelchairs", "vans", "scooters", "finance"],
    startDate: "2026-08-01",
    endDate: "2026-09-01",
    status: "ACTIVE",
    impressions: 18450,
    clicks: 1420,
    createdAt: "2026-08-01T10:00:00Z"
  }
];

